# Generated by Django 4.2.6 on 2023-10-05 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.PositiveIntegerField(unique=True)),
                ('page_title', models.CharField(max_length=200)),
                ('finna_id', models.CharField(blank=True, max_length=200, null=True)),
                ('finna_id_confirmed', models.BooleanField(default=False)),
                ('finna_id_confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phash', models.BigIntegerField(null=True)),
                ('dhash', models.BigIntegerField(null=True)),
                ('dhash_vertical', models.BigIntegerField(null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_hashes', to='images.image')),
            ],
            options={
                'unique_together': {('dhash_vertical', 'image'), ('phash', 'image'), ('dhash', 'image')},
            },
        ),
        migrations.CreateModel(
            name='ImageHashURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_urls', to='images.imagehash')),
            ],
        ),
        migrations.CreateModel(
            name='SdcFinnaID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finna_id', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdc_finna_ids', to='images.image')),
            ],
            options={
                'unique_together': {('image', 'finna_id')},
            },
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='images.image')),
            ],
            options={
                'unique_together': {('image', 'url')},
            },
        ),
    ]
